### ISSUE TITLE
Drop-in UI with Venmo One Touch

### ISSUE THREAD

**Issue by fhackenb** [jeffcarp/braintree-react#9]
I successfully integrated braintree-angular to create a drop-in UI form, and  I was wondering if there's a way to get Venmo OneTouch working with braintree-angular. Here it seems to indicate that all you need to get Venmo OneTouch working is to have the dropin form integrated: https://developers.braintreepayments.com/android+ruby/guides/one-touch/venmo 
Is this only the case for Android and iOS, or is there a way to get it working with braintree-angular?

**Comment by jeffcarp** [comment]
Hi @fhackenb, I think you might have filed this issue in the wrong repo ([braintree-angular](https://github.com/jeffcarp/braintree-angular) and [braintree-react](https://github.com/jeffcarp/braintree-react) have similar sounding names).

Currently OneTouch is only available on Android and iOS (since it requires the ability to natively switch over to the Venmo app).
